const VEHICULOS = [
  {
    id: 1,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Oscuro",
    imagenes: ["imagenes/car-01.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Jeep Gladiator levantado con accesorios off-road de alto rendimiento, listo para cualquier terreno.",
    caracteristicas: ["Traccion 4x4", "Suspension lift kit", "Llantas all-terrain", "Barras de techo", "Ganchos de recuperacion"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 2,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris",
    imagenes: ["imagenes/car-02.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Jeep Gladiator Overland con equipamiento de lujo para aventura y trabajo.",
    caracteristicas: ["Traccion 4x4", "Cama de carga", "Pantalla multimedia", "Apple CarPlay", "Control de crucero adaptativo"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 3,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Oscuro",
    imagenes: ["imagenes/car-03.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Jeep Gladiator Rubicon con capacidades todoterreno extremas y acabados premium.",
    caracteristicas: ["Rubicon 4x4", "Diferenciales delantero y trasero con bloqueo", "Sway bar disconnect", "Rock-Trac", "Llantas Mud-Terrain"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 4,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris",
    imagenes: ["imagenes/car-04.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Jeep Wrangler Unlimited 4-puertas levantado con accesorios de expedicion.",
    caracteristicas: ["4 puertas", "Techo desmontable", "Lift kit", "Barras de proteccion", "Winch frontal"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 5,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2023,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Beis",
    imagenes: ["imagenes/car-05.png"],
    destacado: false,
    condicion: "Usado",
    descripcion: "Jeep Gladiator Rubicon en color beis arena, impecable con bajo kilometraje.",
    caracteristicas: ["Rubicon 4x4", "Cama de 5 pies", "Asientos en cuero", "Pantalla Uconnect", "Climatizador"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 6,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2023,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Beis Champagne",
    imagenes: ["imagenes/car-06.png"],
    destacado: false,
    condicion: "Usado",
    descripcion: "Jeep Gladiator en tono champagne, version equipada con accesorios de serie exclusivos.",
    caracteristicas: ["Traccion 4x4", "Cama de carga reforzada", "Llantas AT", "Barras laterales", "Camara de reversa"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 7,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Rojo",
    imagenes: ["imagenes/car-07.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Jeep Wrangler descapotable en rojo vivo, la experiencia open-air definitiva.",
    caracteristicas: ["Techo removible", "Puertas desmontables", "Motor Pentastar V6", "Traccion Command-Trac", "Faros LED"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 8,
    marca: "Chevrolet",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Deportivo",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Azul",
    imagenes: ["imagenes/car-08.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Chevrolet Corvette C8 con motor central V8 de 495 HP, el superdeportivo americano por excelencia.",
    caracteristicas: ["Motor V8 6.2L mid-engine", "495 HP", "Transmision DCT 8 velocidades", "Magnetorheological suspension", "Frenos Brembo"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 9,
    marca: "BMW",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Sedan",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris",
    imagenes: ["imagenes/car-09.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "BMW M4 Competition con motor twin-turbo de 503 HP, rendimiento y lujo en perfecta armonia.",
    caracteristicas: ["Motor TwinPower Turbo 3.0L", "503 HP", "Transmision M xDrive", "M carbon bucket seats", "M differential"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 10,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Plata",
    imagenes: ["imagenes/car-10.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Jeep Grand Cherokee con interior de lujo y capacidades todo terreno de nivel superior.",
    caracteristicas: ["Quadra-Lift air suspension", "Quadra-Drive II 4x4", "Asientos en cuero Nappa", "McIntosh audio", "Pantalla 10.1 pulgadas"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 11,
    marca: "Ford",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Deportivo",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 0,
    color: "Negro",
    imagenes: ["imagenes/car-11.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Ford Mustang GT negro de alto rendimiento, un icono americano con toda la potencia.",
    caracteristicas: ["Motor V8 5.0L Coyote", "450 HP", "Transmision manual 6 velocidades", "Launch Control", "Track Apps"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 12,
    marca: "Porsche",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Deportivo",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco",
    imagenes: ["imagenes/car-12.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Porsche 911 Carrera 992 en blanco glaciar, el deportivo mas icónico de todos los tiempos.",
    caracteristicas: ["Motor boxer 6 cilindros turbo 3.0L", "385 HP", "PDK 8 velocidades", "PASM sport suspension", "Sport Chrono package"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 13,
    marca: "Mercedes-Benz",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Sedan",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco",
    imagenes: ["imagenes/car-13.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Mercedes-Benz C-Class AMG Line con el refinamiento aleman en su maxima expresion.",
    caracteristicas: ["Motor turbo 2.0L 255 HP", "9G-TRONIC transmision", "Asientos en cuero", "MBUX infotainment", "AMG Line exterior"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 14,
    marca: "Mercedes-Benz",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco",
    imagenes: ["imagenes/car-14.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Mercedes-Benz GLE AMG con potencia brutal y confort de primera clase para toda la familia.",
    caracteristicas: ["Motor AMG biturbo", "E-ACTIVE BODY CONTROL", "7 asientos", "Burmester 3D surround", "MBUX Hyperscreen disponible"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 15,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Negro",
    imagenes: ["imagenes/car-15.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Jeep Gladiator negro levantado con presencia imponente y capacidad off-road extrema.",
    caracteristicas: ["Lift kit de 4 pulgadas", "Llantas 37 pulgadas", "Bumper delantero acero", "Winch 12,000 lbs", "Luces LED adicionales"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 16,
    marca: "Mercedes-Benz",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco",
    imagenes: ["imagenes/car-16.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Mercedes-Benz GLE Coupe AMG con silueta fastback y rendimiento deportivo excepcional.",
    caracteristicas: ["Motor AMG 4.0L V8 biturbo", "Techo panoramico", "Asientos AMG Performance", "Escape AMG", "4MATIC+"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 17,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2023,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Verde Militar",
    imagenes: ["imagenes/car-17.png"],
    destacado: false,
    condicion: "Usado",
    descripcion: "Jeep Gladiator en verde militar oscuro, version personalizada con estilo tatico unico.",
    caracteristicas: ["Traccion 4x4", "Suspension Sport", "Llantas AT 33 pulgadas", "Barras de proteccion", "Camara 360"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 18,
    marca: "Volvo",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "SUV",
    precio: 0,
    precioConsultar: true,
    combustible: "Hibrido",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco",
    imagenes: ["imagenes/car-18.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Volvo XC90 R-Design con tecnologia hibrida enchufable y el maximo confort escandinavo.",
    caracteristicas: ["Motor T8 hibrido enchufable", "455 HP combinados", "7 asientos", "Bowers & Wilkins audio", "Pilot Assist autonomia"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 19,
    marca: "Jeep",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Pickup",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Negro",
    imagenes: ["imagenes/car-19.png"],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Jeep Gladiator negro con preparacion extrema, para quienes exigen lo mejor fuera del asfalto.",
    caracteristicas: ["Lift kit 6 pulgadas", "Llantas 40 pulgadas", "Chasis reforzado", "Diferencial trasero con bloqueo", "Snorkel de admision"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 20,
    marca: "Chevrolet",
    modelo: "Reyes Muñoz Luxury Cars",
    ano: 2024,
    tipo: "Deportivo",
    precio: 0,
    precioConsultar: true,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Rojo",
    imagenes: ["imagenes/car-20.png"],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Chevrolet Camaro SS convertible en rojo vibrante, potencia V8 con el sol en la cara.",
    caracteristicas: ["Motor V8 6.2L 455 HP", "Techo convertible electrico", "Frenos Brembo", "Launch Control", "Pantalla 8 pulgadas"],
    fechaAgregado: "2026-05-01",
    enOferta: false,
    precioAnterior: null
  }
];

// ===== CONSTANTES DE FILTRADO =====
const MARCAS_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.marca))].sort();
const TIPOS_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.tipo))].sort();
const ANOS_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.ano))].sort((a, b) => b - a);
const COMBUSTIBLES_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.combustible))].sort();
